import time
import sys

print ("   Terceiro Capitulo")
time.sleep(0.5)
print("No dia seguinte, o quarteto conspiracionista estava reunido, Jake, Troup, Komissor e Phil. Conversa vai, conversa vem até que um bêbado qualquer (nome dele não vai ser importante pra história) disse que no rancho dos Smallwood a plantação deles foi queimada e foi feito um desenho redondo. ")
time.sleep(6)
print("Phil como estava trabalhando, falou para os três irem averiguar. ")
time.sleep(1)
print("Chegando lá, se deparam com não apenas a plantação com uma forma estranha mas a casa estava pegando fogo, e no quintal estava Smallwood sem vida com o peito queimado assim como o sr. Greyson e sua mulher ao lado com meio corpo queimado em seus últimos segundos de vida disse o seguinte “é uma criatu..ra diferen....te, ele tem uns 3 meee....troos, tem a cor meio rooxa e dispaa....”")
time.sleep(8)
print("Essa foram as últimas palavras da senhora Smallwood. A dúvida estava instaurada na cabeça deles, Jake estava passando mal nesse momento e vomitando até as tripas e falando “cacete eles foram dessa pra uma mió, mas oia o corpo deles”.")
time.sleep(4)
print("Minutos depois, conversando com o xerife, o mesmo disse que achava que era obra da gangue do Cabrone, devido a serem cruéis com quem não lhe “pagassem” (Cabrone era o que conhecemos hoje por, agiota) e até porque, o mesmo estava na cidade.")
time.sleep(6)
print("O trio foi mais que de pressa de encontro a Cabrone e seus parceiros de gangue que estava em um bar de qualidade duvidosa da cidade.\n")
time.sleep(2)

print('+++++++++++++++++++++++++++++++++++++++++++++++++++++++')
time.sleep(1)
print('Escolha a ação de Troup:')
time.sleep(1)
print("1. “Seu vagabundo, o que você estava fazendo hoje cedo?” \n2. “Voltou a matar civis seu verme, eu ainda não esqueci do que falei a ti em New Austin, tenho uma bala com seu nome” \n3. Mete o pé na porta e dispara na cabeça de Cabrone.\n")
time.sleep(1)

esc31 = int(input('Escolha:  '))
print('+++++++++++++++++++++++++++++++++++++++++++++++++++++++')
time.sleep(1)
if esc31 == 1 or esc31 == 2:
    print("- Cabrone: tu estas me ameaçando? Hahaha")
    time.sleep(2)
    print("- Troup: não preciso ameaçar, o que é seu está guardado.")
    time.sleep(2)
    print("- Cabrone: Trouxe até seu escudeiro ai, dia de sorte, vou matar 3 branquelos numa cajadada só")
    time.sleep(3)
    print("- Komissor: Você pode me levar na crocodilagem, mas levo dois comigo ")
    time.sleep(2)
    print("Jake nesse momento estava com as partes tremendo...")
    time.sleep(2)
    print("- Troup: Se a última bala que gastar em vida for em você, morro feliz.")
    time.sleep(2)
    print("- Cabrone: Yo gosto de tu amigo hahahaha. Diga me o que quieres")
    time.sleep(2)
    print("- Troup: Quero saber o motivo que você matou os Smallwood")
    time.sleep(1)
    print("- Cabrone: Yo não matei ninguém amigo, gosto do Smallwood e de sua mulher principalmente")
    time.sleep(3)
    print("- Troup: Então o que faz por Nockville?")
    time.sleep(1)
    print("- Cabrone: Fiquei sabendo de um assassino de civis, e só eu posso matar essas bundas brancas haha ou é você com seu amigo cor de leite, voltaram a matar igual dois bois enfurecidos amigo?")
    time.sleep(5)
    print("- Troup:  Não, eu nunca mais matei ninguém")
    time.sleep(1)
    print("- Cabrone: hahahaha o pessoal dessa cidade não sabe o que tu fizeste em Chuparosa e Gandito não é hahah")
    time.sleep(3)
    print("- Komissor: vamos embora")
    time.sleep(1)

    print('+++++++++++++++++++++++++++++++++++++++++++++++++++++++')
    time.sleep(1)
    print('Escolha a ação de Troup:')
    time.sleep(1)
    print("1. Vai embora \n2. Ameaça Cabrone\n")
    time.sleep(1)
    esc32 = int(input('Escolha:  '))
    print('+++++++++++++++++++++++++++++++++++++++++++++++++++++++')
    time.sleep(1)
    if esc32 == 2:
        print("- Troup: Aproveita essa visita na cidade, pode ser sua última vez por essas terras.")
        time.sleep(2)
        print("- Cabrone: Você não sabe do que sou capaz garoto.")
        time.sleep(1)
elif esc31 == 3:
    print("Troup e seus amigos são mortos pela gangue de Cabrone que estava em maioria no local.")
    time.sleep(2)
    print("Fim.")
    sys.exit()

print ("   Quarto Capitulo")
time.sleep(0.5)
print("Uma semana, após isso. Troup e Komissor estavam andando por Nockville as 6 da manhã relembrando os bons (e maus) momentos que tiveram desbravando o Oeste e a costa mexicana. ")
time.sleep(4)
print("Até que escuta uma pessoa vindo de longe gritando, até que perceberam que era Jay Clarkson.")
time.sleep(2)
print("Sem um braço, mais que de pressa eles pegaram Jay e levaram ao doutor da cidade. ")
time.sleep(2)
print("Jay dizia repetidamente: “eu vi, eu vi, ele existe”. A dupla se assustou com aquilo e após acordar o médico derrubando a porta de sua casa. ")
time.sleep(4)
print("O doutor disse que ele tinha perdido muito sangue, para deixar ele e mais tarde voltar.")
time.sleep(2)
print("Nisso, Troup foi ao bar conversar com Phil mas para sua surpresa Phil não estava lá. Resolveu ir ao rancho dos Clarkson. Chegando lá, o cenário era de destruição.")
time.sleep(4)

print('+++++++++++++++++++++++++++++++++++++++++++++++++++++++')
time.sleep(1)
print('Escolha a ação de Troup:')
time.sleep(1)
print("1. Volte correndo a cidade e vá falar com Komissor. \n2.	Investigue o rancho.\n")
time.sleep(1)
esc41 = int(input('Escolha:  '))
print('+++++++++++++++++++++++++++++++++++++++++++++++++++++++')
time.sleep(1)
if esc41 == 1:
    print("Troup volta a cidade e vai direto a porta do médico se encontrar com Komissor. E o Alemão diz que Jay tinha morrido.")
    time.sleep(2)
    print("Os dois decidem ir ao rancho verificar se existe alguma coisa lá, chegando lá olham pela casa destruída e não encontram nada, até escutarem um barulho vindo do porão. ")
    time.sleep(4)
    print("Após abrir a tampa do porão se deparam com Phil extremamente machucado e com um pedaço estranho roxo em sua mão. ")
    time.sleep(2)
    print("Phil contou que viu o suposto bicho e que ele se assemelhava a um humano que disparava com a ponta dos dedos e tinha um serrote em seu cotovelo.")
    time.sleep(4)
    print("Além de que o “grandão” era resistente a balas.")
    time.sleep(2)

    print('+++++++++++++++++++++++++++++++++++++++++++++++++++++++')
    time.sleep(1)
    print('Escolha a pergunta de Troup:')
    time.sleep(1)
    print("1. Como você sobreviveu? Como você cortou esse pedaço dele \n2. Vem, vou te levar ao medico \n3. Seu irmão morreu...\n")
    time.sleep(1)
    esc42 = int(input('Escolha:  '))
    print('+++++++++++++++++++++++++++++++++++++++++++++++++++++++')
    time.sleep(1)
    if esc42 == 1:
        print("Phil respondeu: ")
        time.sleep(2)
        print("Eu só lembro dele mirando e disparando um raio em mim, daí não lembro de nada e nem de como vim parar aqui... na verdade... ele pisou em uma estrutura de madeira pontiaguda que deixamos no campo...tanto que quando cheguei vi isso la e peguei na mão, foi ai que me deparei com ele.")
        time.sleep(6)
    elif esc42 == 2:
        print("Phil respondeu: ")
        time.sleep(2)
        print("Ok, vamos. Mas calma lá vou contar o que vi do bicho, lembro dele mirando e disparando um raio em mim, daí não lembro de nada e nem de como vim parar aqui... na verdade... ele pisou em uma estrutura de madeira pontiaguda que deixamos no campo...tanto que quando cheguei vi isso la e peguei na mão, foi ai que me deparei com ele.")
        time.sleep(7)
    elif esc42 == 3:
        print("Phil respondeu: ")
        time.sleep(2)
        print("Não, como assim, não... não....")
        time.sleep(2)
        print("Phil foi levando em prantos ao médico e no final daquela noite, o médico chamou Troup e Komissor pois Phil queria contar como era o bicho. ")
        time.sleep(3)
        print("“Lembro dele mirando e disparando um raio em mim, daí não lembro de nada e nem de como vim parar aqui... na verdade... ele pisou em uma estrutura de madeira pontiaguda que deixamos no campo...tanto que quando cheguei vi isso la e peguei na mão, foi ai que me deparei com ele. ”")
        time.sleep(6)
elif esc41 == 2:
    print("Troup vasculha a casa e não encontra nada, até se deparar com um barulho vindo do porão, quando ele abre a porta, se depara com Phil extremamente machucado e com um pedaço estranho roxo em sua mão. ")
    time.sleep(4)
    print("Phil contou que viu o suposto bicho e que ele se assemelhava a um humano que disparava com a ponta dos dedos e tinha um serrote em seu cotovelo. Além de que o “grandão” era resistente a balas.")
    time.sleep(4)

    print('+++++++++++++++++++++++++++++++++++++++++++++++++++++++')
    time.sleep(1)
    print('Escolha a pergunta de Troup:')
    time.sleep(1)
    print("1. Como você sobreviveu? Como você cortou esse pedaço dele \n2. Vem, vou te levar ao medico \n")
    time.sleep(1)
    esc43 = int(input('Escolha:  '))
    print('+++++++++++++++++++++++++++++++++++++++++++++++++++++++')
    time.sleep(1)
    if esc43 == 1:
        print("Phil respondeu: ")
        time.sleep(2)
        print("Eu só lembro dele mirando e disparando um raio em mim, daí não lembro de nada e nem de como vim parar aqui... na verdade... ele pisou em uma estrutura de madeira pontiaguda que deixamos no campo...tanto que quando cheguei vi isso la e peguei na mão, foi ai que me deparei com ele.")
        time.sleep(6)
    elif esc43 == 2:
        print("Phil respondeu: ")
        time.sleep(2)
        print("- Ok, vamos. ")
        time.sleep(1)
        print("- Mas calma lá vou contar o que vi do bicho, lembro dele mirando e disparando um raio em mim, daí não lembro de nada e nem de como vim parar aqui... na verdade... ele pisou em uma estrutura de madeira pontiaguda que deixamos no campo...tanto que quando cheguei vi isso la e peguei na mão, foi ai que me deparei com ele.")
        time.sleep(7)
        print("Chegando no médico, Komissor chama Troup de canto e conta que Jay havia morrido, devido ao incessante sangramento.")
        time.sleep(3)