import time

print ("   Primeiro Capitulo")
time.sleep(0.5)
print ("O ano é 1905, em Nockville. Uma cidade pacata desde o fim da época do ouro, certo dia, um dos seus moradores, o sr. Grayson foi até a delegacia reportar que viu um objeto flutuante por volta de sua casa. O xerife deu risada e falou para ele se retirar e indicou ele ir ao médico. Jake Bag que tinha uma mente avoada foi atrás de Grayson para mais detalhes de sua história. Ah, o dia? 20 de janeiro.")
time.sleep(5)
print ('Quase um mês após isso, dia 15 de fevereiro, Grayson foi encontrado morto frente a seu milharal em sua fazenda, e de uma forma que não se vê por ai, ao redor do imenso corte em seu peito estava tudo queimado. Rapidamente ligaram isso a gangue dos cabritos. Por Grayson já ter tido desavenças com o Cabrone.')
time.sleep(5)
print ('Jake Bag foi ao rancho de Troup, que dá uns 20 minutos de cavalo da cidade e foi contar isso ao seu melhor amigo.')
time.sleep(2)
print('“Trô, ucê num acredita, Grayson bateu as bota e essa história ta estranha, sabe o que é acho q é o pé grande, lembra q seu pai contava pa nói depoi da aula. Grayson falô que viu um bichão grandão sentadão numa bola e se movendo pelo cér tipo um pássaro. To cabreirão com isso"')
time.sleep(3)
print('+++++++++++++++++++++++++++++++++++++++++++++++++++++++')
time.sleep(1)
print('Diante disso, escolha o que Troup vai falar:')
time.sleep(1)
print ("1. Jake hahaha você já ta chapadão? \n2. Cara, vamos verificar isso, se você diz eu confio. \n3. Eu sempre desconfiei desse tal de pé grande.")
time.sleep(2)
esc = int(input('Escolha:  ' ))
print('+++++++++++++++++++++++++++++++++++++++++++++++++++++++')
if esc ==1:
    time.sleep(1)
    print ('Jake: Um poquin só hehe')
    time.sleep(0.5)
elif esc == 2:
    time.sleep(1)
    print ('Jake: porisso confio minha vida em você meu amigo')
    time.sleep(0.5)
elif esc == 3:
    time.sleep(1)
    print('Jake: Num é, lembro q seu pai contava e eu nem dormia direito')
    time.sleep(0.5)
else:
    print ('erro')
    
print ("---------------------------------------------------------------------------------------------------------------------------------------------------")
time.sleep(0.5)
print ("    Segundo Capitulo")
time.sleep(2)
print("Certo dia, na madrugada, Troup ainda com a história de Jake na cabeça estava no bar dos Clarkson, depois de uns goró e de ganhar uma graninha no Poker resolveu falar com dois caras de sua confiança, os donos do bar, Phil e Jay")
time.sleep(3)
print (" -Troup: Vocês ouviram falar da história do Grayson?")
time.sleep(2)
print (' -Jay: Aquele velho louco pão-duro? Foi tarde')
time.sleep(2)
print (' -Phil: Qual é Jay, fala dele assim não')
time.sleep(2)
print(' -Jay: Ele recusou dar um serviço a nós quando estávamos quebrados bródi.')
time.sleep(2)
print (' -Phil: Mas ele tinha os motivos dele na época, quem ia confiar em nós?')
time.sleep(2)
print(' -Troup: Vocês acreditam na história do pé grande?')
time.sleep(2)
print (' -Jay: HAHAHAHAH Troup falei pra você para com o Whisky')
time.sleep(2)
print ('Phil se aproxima e solta:')
time.sleep(3)
print ('-Eu acredito, Deus me permita crer em tudo mi amigo')
time.sleep(2)
print (' -Troup:  Mas isso será possível? Tipo, Jake me disse que ele voava tipo um pássaro mas sentado em uma cabine.')
time.sleep(2)
print (' -Jay: Meu bar virou hospício em questão de minutos, eu vou embora dormir.')
time.sleep(2)
print (' -Phil: Troup... Jake nunca mentiu a ti, você precisa acreditar, eu acredito pois já vi Deus e sempre vou crer no inacreditável. Caso isso for tudo uma ladainha, ele vai ter outro motivo pra sempre zoar ele hahaha.')
time.sleep(2)
print('+++++++++++++++++++++++++++++++++++++++++++++++++++++++')
time.sleep(1)
print ('Diante disso, qual a melhor ação de Troup: ')
time.sleep(0.5)
print('1. Ir atrás de Jake e conversar mais sobre essa história \n2. Ir dormir e esquecer essa loucura.')
time.sleep(1)
esc2 = int(input('Escolha:  '))
print('+++++++++++++++++++++++++++++++++++++++++++++++++++++++')
if esc2 ==1:
    time.sleep(1)
    print ('Troup chega a casa de Jake e bate repetidamente na porta, até escutar um “pode entra chefe”, quando abre a porta, Troup se depara com um antigo conhecido, Komissor. ')
    time.sleep(2)
    print('-Troup: Komissor? Que surpresa boa')
    time.sleep(2)
    print('-Komissor: Eaí mãozinha')
    time.sleep(2)
    print('-Troup: O que lhe trouxe por essa área novamente?')
    time.sleep(2)
    print('-Komissor: Eu estava em Chola Springs e você sabe como é, por onde eu vou, tem gente querendo chutar meu traseiro. Aqui é o único lugar que consigo ter paz')
    time.sleep(2)
    print('-Troup: E como tu encontrou o Jake?')
    time.sleep(2)
    print('-Jake: Hehehe to aprendendo a dar uns tiros, e tiro mesmo, de garrucha dessa vez hehe')
    time.sleep(2)
    print('-Komissor: Estava no Clarkson e o Phil me contou um pouco sobre essa história e seu amigo tagarela ai, mais que de pressa, saiu do 21 e veio encher meu saco.')
    time.sleep(2)
    print('-Jake: Oloco alemão, fala assim de mim não')
    time.sleep(2)
    print('-Troup: E você acredita nessa história?')
    time.sleep(2)
    print('-Komissor: Amigo, eu já vi coisas e já fiz coisas que jamais imaginaria fazer ou ver. Então, a única coisa que não acredito é que alguém consegue ser mais veloz que eu, de resto, creio.')
    time.sleep(2)
    print('+++++++++++++++++++++++++++++++++++++++++++++++++++++++')
    time.sleep(1)
    print('Escolha a ação de Troup:')
    time.sleep(1)
    print('1.Então agora somos um trio. \n2Até tu ta louco meu amigo? \n3.Bora no Clarkson, temos muito o que conversar.')
    time.sleep(1)
    esc3 = int(input('Escolha:  '))
    print('+++++++++++++++++++++++++++++++++++++++++++++++++++++++')
elif esc2 == 2:
    time.sleep(1)
    print ('No dia seguinte, andando pelas ruas, vê Jake e Komissor entrando no saloon dos Clarkson. ')
    time.sleep(2)
    print('-Troup: Komissor? Que surpresa boa')
    time.sleep(2)
    print('-Komissor: Eaí mãozinha')
    time.sleep(2)
    print('-Troup: O que lhe trouxe por essa área novamente?')
    time.sleep(2)
    print('-Komissor: Eu estava em Chola Springs e você sabe como é, por onde eu vou, tem gente querendo chutar meu traseiro. Aqui é o único lugar que consigo ter paz')
    time.sleep(2)
    print('-Troup: E como tu encontrou o Jake?')
    time.sleep(2)
    print('-Jake: Hehehe to aprendendo a dar uns tiros, e tiro mesmo, de garrucha dessa vez hehe')
    time.sleep(2)
    print('-Komissor: Ontem à noite, estava aqui no Clarkson e o Phil me contou um pouco sobre essa história e seu amigo tagarela ai, mais que de pressa, saiu do 21 e veio encher meu saco.')
    time.sleep(2)
    print('-Jake: Oloco alemão, fala assim de mim não')
    time.sleep(2)
    print('-Troup: E você acredita nessa história?')
    time.sleep(2)
    print('-Komissor: Amigo, eu já vi coisas e já fiz coisas que jamais imaginaria fazer ou ver. Então, a única coisa que não acredito é que alguém consegue ser mais veloz que eu, de resto, creio.')
    time.sleep(2)
    print('+++++++++++++++++++++++++++++++++++++++++++++++++++++++')
    time.sleep(1)
    print('Escolha a ação de Troup:')
    time.sleep(1)
    print('1.Então agora somos um trio. \n2.Bora se reunir aqui hoje à noite, temos muito o que conversar.')
    time.sleep(1)
    esc3 = int(input('Escolha:  '))
    print('+++++++++++++++++++++++++++++++++++++++++++++++++++++++')
else:
    print ('erro')


    
time.sleep(2)
print ('---------------------------------------------------------------------------------------------------------------------------------------------------')
time.sleep(0.5)
print ("    Terceiro Capitulo")


