import time

print ("   Quinto Capitulo")
time.sleep(0.5)
print ("Analisando o mapa da cidade e de suas redondezas, Troup, Jake e Komissor notaram que o suposto bicho seguia uma lógica e estava atacando cada vez mais próximo de Nockville. E pelo mapa que pegaram com o xerife, a próxima vítima seria o próprio Troup. Pelo histórico do bichano atacar de noite para madrugada, eles resolveram ficar na cidade até o início da noite e ir para o rancho preparados.")
time.sleep(7)
print ('O trio tentou convidar algumas pessoas da cidade a ir junto deles mas ninguém teve coragem. A cidade estava lotada, de pessoas e de medo. Ninguém mais tinha coragem de ir seu rancho por medo do tal animal. ')
time.sleep(4)
print ('Até que deu o horário e foi o trio parada dura ao rancho do Troup. Era visível a tensão no Jake, e de certa forma, até o ar de Troup estava tenso, por mais que ele já tenha matado tudo que ande e rasteje pelo solo, fazia muito tempo que ele não fazia aquilo. Komissor estava com um semblante sério e frio, como sempre.')
time.sleep(6)
print('Chegando no rancho, perceberam que estava tudo pegando fogo já. Porém ao se aproximarem perceberam que a gangue dos cabritos estava ali ateando fogo na residência do Troup.')
time.sleep(3)
print('+++++++++++++++++++++++++++++++++++++++++++++++++++++++')
time.sleep(1)
print('Escolha a ação de Troup:')
time.sleep(1)
print ("1. Sai disparando \n2. Fala para Komissor ir pelo flanco direito e no flanco esquerdo, leva Jake para ter noção da situação.")
time.sleep(1)
esc51 = int(input('Escolha:  '))
print('+++++++++++++++++++++++++++++++++++++++++++++++++++++++')
time.sleep(1)
if esc51 ==1:
    time.sleep(1)
    print ('Leva alguns dos cabritos na bala, porém leva um tiro na perna ')#( -25 de saúde).
    time.sleep(1)
    print('-Cabrone: Olha só quem está aqui haha tu não teve coragem de me ameaçar seu rato')
    time.sleep(2)
    print('-Troup: Hoje é seu dia final seu mexicano bastardo.')
    time.sleep(2)
    print('-Komissor: TROUP! Olha para o céu')
    time.sleep(2)
    print('Sim, era aquela cabine do Bicho, iluminando todo o campo e transformando a noite em dia. Todos pararam para “apreciar” aquilo. Até que a criatura sai do seu objeto voador e começa a disparar e atacar os homens do Cabrone.')
    time.sleep(3)
    print('+++++++++++++++++++++++++++++++++++++++++++++++++++++++')
    time.sleep(1)
    print('Escolha a ação de Troup:')
    time.sleep(1)
    print ("1. Gritar para seus amigos e fugir dali o mais rápido possível. \n2. Tentar matar de vez a fera. \n3. Aproveitar a vantagem e matar Cabrone e seus homens")
    time.sleep(1)
    esc52 = int(input('Escolha:  '))
    print('+++++++++++++++++++++++++++++++++++++++++++++++++++++++')
    time.sleep(1)
    if esc52 == 1:
        time.sleep(0.5)
        print('O trio consegue fugir, assustados, voltam correndo desesperados para cidade. ')
    elif esc52 == 2:
        time.sleep(0.5)
        print('O monstro percebe os tiros vindo em sua direção e ataca Komissor e Troup. Jake consegue fugir, Komissor carrega Troup machucado até a cidade.') #-70 de saúde
    elif esc52 == 3:
        time.sleep(0.5)
        print('O que parecia vantagem se transforma em desvantagem, o bichano percebe os tiros e dispara contra o trio. Jake e Komissor carregam Troup e voltam a cidade.') #-40 de saúde
elif esc51 == 2:
    time.sleep(1)
    print ('Komissor percebe a quantidade de Cabritos por ali, e no velho truque que o mesmo tinha de identificação com o Troup. Eles se reúnem novamente e percebem que existem cerca de 15 a 20 da gangue adversária por lá. Até que escutam um grito:')
    time.sleep(3)
    print('-Cabrone: Cadê você frangalha, eu vim aqui te dar o que você merece, a morte.')
    time.sleep(2)
    print('De repente surge um objeto no céu, iluminando todo o campo e transformando a noite em dia. Todos pararam para “apreciar” aquilo. Até que a criatura sai do seu objeto voador e começa a disparar e atacar os homens do Cabrone.')
    time.sleep(2)
    print('+++++++++++++++++++++++++++++++++++++++++++++++++++++++')
    time.sleep(1)
    print('Escolha a ação de Troup:')
    time.sleep(2)
    print('1. Fugir o mais rápido possível \n2. Tentar matar de vez a fera \n3. Observar um pouco como a fera age')
    time.sleep(1)
    esc53 = int(input('Escolha:  '))
    print('+++++++++++++++++++++++++++++++++++++++++++++++++++++++')
    time.sleep(1)
    if esc53 ==1:
        time.sleep(1)
        print('O trio consegue fugir, assustados, voltam correndo para cidade. Porém Cabrone percebe a movimentação na parte de cima do rancho e atira em direção a eles, que pega em Troup ')#-30 de saúde
    elif esc53 == 2:
        time.sleep(1)
        print ('O monstro percebe os tiros vindo em sua direção e ataca Komissor e Troup. Jake consegue fugir, Komissor carrega Troup machucado até a cidade.')#-70 de saúde
    elif esc53 == 3:
        time.sleep(1)
        print ('Abaixados no mato, observam o monstro pegar o Cabrone com a mão e literalmente dividi-lo em duas partes. Até Troup arregalou os olhos vendo o seu arqui-inimigo ser destroçado como se fosse algodão. Jake deve estar vomitando até agora, mas enfim, após assistirem isso, o trio mais que de pressa fugiu dali.')            
time.sleep(2)
print ("---------------------------------------------------------------------------------------------------------------------------------------------------")
time.sleep(1)
print ("    Sexto Capitulo")
time.sleep(1)
print('Após voltarem a cidade, Troup estava ferido, Jake e Komissor incrédulos com o que acabaram de ver. Aquilo era real e extremamente letal. Komissor estava enfaixando o machucado de Troup nesse momento, até Jake que não sabe rezar, estava no chão, ajoelhado.')
time.sleep(4)
print ('-Jake: Pai do cér, eu não quero morrer assim não, desculpa meus pecado, mas favorzin quero morrer véio com uns fi bonito e crescido.')
time.sleep(2)
print('-Komissor: Cala a boca Jake! Nós vamos matar o pescoçudo assassino.')
time.sleep(2)
print ('-Troup: Lemão, vai com o xerife e pega o mapa da região. ')
time.sleep(2)
print ('O alemão chega com o mapa da cidade, abre a porta e diz: “Fodeu! ”.')
time.sleep(2)
print ('Jake pergunta o porquê, mais que de pressa tem a resposta:')
time.sleep(2)
print('-Se o monstro continuar seguindo seu rastro de destruição, a cidade é a próxima vítima. Ele sempre está seguindo a leste dos ranchos.')
time.sleep(2)
print('+++++++++++++++++++++++++++++++++++++++++++++++++++++++')
time.sleep(1)
print('Escolha a ação de Troup:')
time.sleep(1)
print('1. Vamos evacuar a cidade  \n2. Não vamos permitir ele chegar até aqui')
time.sleep(1)
esc60 = int(input('Escolha:  '))
print('+++++++++++++++++++++++++++++++++++++++++++++++++++++++')
time.sleep(1)
if esc60 == 1:
    time.sleep(1)
    print ('A mando de Troup, Komissor vai a um saloon da cidade e Jake ao outro pedindo para o pessoal evacuar a cidade e contando que eles viram o monstro.')
    time.sleep(2)
    print('Bafafa gerado, alguns acreditavam, mas a maioria das pessoas os chamavam de loucos.')
    time.sleep(2)
    print('Phil deu voz a Jake no saloon, dizendo que viu a criatura e que ela matou seu irmão. Phil tinha uma voz importante na cidade, o que fez alguns outros acreditarem. ')
    time.sleep(3)
    print('Pelo lado bom, cerca de 5 homens se disponibilizaram a ajudar.')
    time.sleep(1)
    print('Enquanto isso, Troup conversava com o Xerife Cartwright. Após muita conversa, o xerife e seu delegado acreditaram no que Troup diz. ')
    time.sleep(2)
    print('Logo pela manhã, o xerife saiu pedindo para as pessoas saírem da cidade por um dia, alguns rancheiros abriram seus estábulos para receber pessoas. O caos estava instaurado na cidade, xerife teve que prender alguns delinquentes que se recusaram a partir.')
    time.sleep(4)
    print('Xerife pergunta se Troup tem alguma estratégia:')
    time.sleep(1)
    print('+++++++++++++++++++++++++++++++++++++++++++++++++++++++')
    time.sleep(1)
    print('Escolha a ação de Troup:')
    time.sleep(1)
    print('1. Tenho uma estratégia  \n2. Não tenho nada definido')
    time.sleep(1)
    esc61 = int(input('Escolha:  '))
    print('+++++++++++++++++++++++++++++++++++++++++++++++++++++++')
    time.sleep(1)
    if esc61 == 1:
        time.sleep(1)
        print('-Troup: Sim xerife, eu pensei em separar algumas armadilhas nos arredores da cidade e dispersar os homens. Deixam alguns dos piores atiradores nas partes altas de cada rua para avisar caso o bichano estiver vindo. E os velocistas aqui no papel cruel de distrair o bicho. Pois como ele é imune a bala penso que apenas com objetos cortantes vamos conseguir mata-lo.')
        time.sleep(5)
        print('-Xerife: É muito arriscado, não é melhor deixar alguns atiradores a uma boa distância?')
        time.sleep(2)
        print('-Troup: Ele resiste a tiros...')
        time.sleep(2)
        print('O dia ia passando e os guerreiros de Nockville iam se preparando, como a cidade estava vazia e o xerife permitiu, eles entraram em diversos estabelecimentos para pegar o que seria útil e formar uma armadura improvisada.')
        time.sleep(3)
        print ('Começou a anoitecer, a equipe estava separada e cada um no lugar marcado. Komissor e o delegado armaram diversas armadilhas com facas. ')
        time.sleep(2)
        print('Phil e Jake estavam juntos de alguns civis em telhados pela cidade. Troup, Komissor, xerife, delegado e dois ex-militares estavam separados, mas nas duas entradas da cidade. Que o terreno plano ajudava a vigia. O frio na barriga era presente em todos, parecia que o dia não passava.')
        time.sleep(4)
        print('Até que após anoitecer, finalmente escutam o que esperavam, mas não queriam ouvir: “MEU DEUS O QUE É AQUILO NO CÉU? ”. Jake avista e berra: “É ELE! ”')
        time.sleep(3)
        print('O monstro pisa no solo, e já começa a disparar e ir de encontro aos cidadãos de Nockville. Dois civis em telhados ficam em estado de choque e caem lá de cima. Cada um tinha uma armadilha a levar o bicho, xerife levou ele certinho a armadilha de facas colocadas na frente de um mercadinho local. Entrou lá e deu uma risadinha após escutar o barulho da armadilha ativada, para sua surpresa uma imensa mão o puxa pela porta. Fim da linha para o xerife.')
        time.sleep(5)
        print('Alguns até tentavam dar tiros para distrai-lo, mas não adiantava. O delegado após ver a morte de seu melhor amigo que saiu de sua posição e foi de encontro com o monstro. Bom, coitado...')
        time.sleep(4)
        print('A turma estava em 11, e em menos de 3 minutos 4 já estavam fora de combate. ')
        time.sleep(1)
        print('+++++++++++++++++++++++++++++++++++++++++++++++++++++++')
        time.sleep(1)
        print('Escolha a ação de Troup')
        time.sleep(1)
        print('1. Cada um fica aonde está  \n2. Pede para o grupo se reunir')
        time.sleep(1)
        esc62 = int (input('Escolha:  '))
        print('+++++++++++++++++++++++++++++++++++++++++++++++++++++++')
        time.sleep(1)
        if esc62 == 1:
            time.sleep(1)
            print ('Assustado, Jake escorrega no telhado e quebra algumas telhas. Nisso mais que de pressa o bichano parte para o local, Jake percebe corre para dentro da marcenaria e se esconde atrás de algumas vigas. Komissor estava mais perto do local e vai correndo em direção a eles. Troup um pouco mais distante vai também.')
            time.sleep(3)
            print('Jake segurava o terço que tinha pegado naquele mesmo dia na Igreja, o bicho quebra tudo e estava lá dentro. Localiza Jake e o arremessa para o fundo da marcenaria. Jake extremamente machucado pegou um pedaço de madeira pontiagudo que foi gerado após o monstro o tacar na parede. E assim que o bichano chega perto, Jake enfia a madeira e roda. O monstro solta um grunhido e joga o caipira no meio da rua, porém era visível que ele estava sangrando.')
            time.sleep(5)
            print('+++++++++++++++++++++++++++++++++++++++++++++++++++++++')
            time.sleep(1)
            print ('Escolha a ação de Troup')
            time.sleep(1)
            print('1. Vai até Jake e pede para o Komissor ir enfrentar o bicho \n2.Vai até o bicho e pede para o Komissor ajudar o Jake')
            time.sleep(2)
            esc63 = int(input('Escolha:   '))
            print('+++++++++++++++++++++++++++++++++++++++++++++++++++++++')
            time.sleep(1)
            if esc63 == 1:
                time.sleep(0.5)
                print ('-Troup: Komissor, tenta distrair o bicho, vou até o Jake.')
                time.sleep(2)
                print ('-Komissor: Ok')
                time.sleep(1)
                print('Troup chega na rua e segura Jake, quase sem vida.')
                time.sleep(2)
                print('-Troup: Jake, mantém o olho aberto, firme, firme. Você não é um homem de fé agora?')
                time.sleep(2)
                print ('-Jake: eta éé for...te memo maaaas...mas.. da madeirada madeira..nele...')
                time.sleep(2)
                print('-Troup: Que? ')
                time.sleep(1)
                print('-Jake: Ele..e.. não éééé.. i..mune.. a madeira')
                time.sleep(2)
                print('Nisso Troup, vai correndo a marcenaria e vê o bicho indo em direção a Komissor já machucado mas para sua surpresa, o bicho estava sangrando e lento.')
                time.sleep(2)
                print('Troup pega um pedaço de madeira pontiaguda que achou no chão e pula nas costas e começa a enfincar no monstro inúmeras vezes. Finalmente o gigante estava desmoronando. ')
                time.sleep(2)
                print ('-Komissor: nós conseguimos meu amigo...')
                time.sleep(2)
                print ('-Troup: Cacete, nós conseguimos')
                time.sleep(2)
                print('Troup leva Jake ao médico que estava no estábulo do rancho do Sr. Dickens.')
                time.sleep(3)
                print('Em Nockville, Komissor com os outros dois sobreviventes que ficaram na cidade armam uma fogueira enorme para queimar o monstro. Cada um com seu whisky brinda a vitória da cidade. ')
            elif esc63 == 2:
                #-40 de saúde
                time.sleep(0.5)
                print('-Troup: Komissor, vai ver o Jake, vou distrair o bicho.')
                time.sleep(1)
                print('-Komissor: Ok')
                time.sleep(1)
                print('Komissor chega na rua e segura Jake, quase sem vida.')
                time.sleep(2)
                print('-Komissor: Caipira, mantém o olho aberto, firme, aguenta as pontas.')
                time.sleep(2)
                print('-Jake: eta éé for...te memo maaaas...mas.. da madeirada madeira..nele...')
                time.sleep(2)
                print('-Komissor: Não entendi caipira')
                time.sleep(2)
                print('-Jake: Da...aa.. madeira..da nelee..')
                time.sleep(2)
                print('Nisso Komissor, vai correndo a marcenaria e vê o bicho indo em direção a Troup já machucado mas para sua surpresa, o bicho estava sangrando e lento.')
                time.sleep(2)
                print('Komissor pega um pedaço de madeira pontiaguda que achou no chão e pula nas costas e começa a enfincar no monstro inúmeras vezes. Finalmente o gigante estava desmoronando. ')
                time.sleep(3)
                print('-Troup: Parece que conseguimos')
                time.sleep(2)
                print('-Komissor: Morra seu verme!!')
                time.sleep(2)
                print('Troup leva Jake ao médico que estava no estábulo do rancho do Sr. Dickens.')
                time.sleep(3)
                print('Em Nockville, Komissor com os outros dois sobreviventes que ficaram na cidade armam uma fogueira enorme para queimar o monstro. Cada um com seu whisky brinda a vitória da cidade.') 
        elif esc62 ==2:
            time.sleep(1)
            print('-Troup: Atenção, vamos nos reunir. Não façam barulho.')
            time.sleep(2)
            print('Todos estavam no Saloon, pensando no que poderia ser feito. O desespero era visível. Antes que eles tivessem a oportunidade de discutir alguma estratégia. Eles escutam o barulho pesado da pisada do gigante. ')
            time.sleep(4)
            print ('Cada um sai para um canto, Komissor se esconde e observa o bicho. Ele destrói a entrada do Saloon porém aquela entrada tinha um pedaço firme de madeira que Phil nunca consertou apesar do povo reclamar. Komissor percebe que o bicho jorrou um liquido laranja assim que passou por ali. Mais que de pressa ele saiu correndo gritando “MADEIRA MACHUCA ELE, MADEIRA MACHUCA ELE”.')
            time.sleep(6)
            print('Com os gritos, não havia dúvida quem seria perseguido pelo bicho. Jake que estava ao lado de Troup lembrou que na loja de armas, vendiam arco e flechas para “treino” em que a ponta das flechas eram de madeira.')
            time.sleep(4)
            print('+++++++++++++++++++++++++++++++++++++++++++++++++++++++')
            time.sleep(1)
            print ('Escolha a ação de Troup:  ')
            time.sleep(1)
            print('1. Fala para Jake ir buscar arcos e flechas, enquanto isso vá ajudar Komissor \n2. Vai buscar os arcos e flechas e deixe Jake ajudar Komissor.')
            time.sleep(2)
            esc64 = int(input('Escolha:'))
            print('+++++++++++++++++++++++++++++++++++++++++++++++++++++++')
            time.sleep(1)    
            if esc64 == 1:
                time.sleep(1)
                print('-Troup: Jake, vá buscar esses arcos e traga o mais rápido possível, se for o caso dê alguns aos London e ao Reyes (ex militares). Vai !!')
                time.sleep(3)
                print('-Jake: Bele')
                time.sleep(2)
                print('Komissor estava levando o monstro a marcenaria, Troup ia pelo flanco acompanhando até que o bichano acerta um tiro laser nas pernas de Komissor que berrava de dor, quando o bicho se aproximou para finalizar o alemão, se escuta um grito do além: “PAU NESSE FÊI LASQUERAAA”')
                time.sleep(4)
                print('Jake, Reyes, London e Phil estavam na entrada da rua atirando as flechas de madeira. Troup aproveitou e pegou um pedaço pontiagudo de madeira na entrada da marcenaria para finalizar o gigante roxo.')
                time.sleep(3)
                print('Troup leva Komissor ao médico que estava no estábulo do rancho do Sr. Dickens.')
                time.sleep(3)
                print('Em Nockville, Jake com os outros dois sobreviventes que ficaram na cidade armam uma fogueira enorme para queimar o monstro. Cada um com seu whisky brinda a vitória da cidade. ')
                time.sleep(2)
            elif esc64 == 2:
                time.sleep(1)
                print('-Troup: Jake, vá ajudar o Komissor. Acompanha ele na corrida pelo flanco da rua')
                time.sleep(3)
                print ('-Jake: Ok, não é melhor eu ir pegar as armas que sou mais rápido?')
                time.sleep(3)
                print ('Komissor estava levando o monstro a marcenaria, Troup ia pelo flanco acompanhando até que o bichano acerta um tiro laser nas pernas de Komissor que berrava de dor, quando o bicho se aproximou para finalizar o alemão, se escuta um grito do além: “PEGA EU FEIÃO”. ')
                time.sleep(5)
                print('O monstro largou o Komissor e foi pegar Jake, porém nesse momento Troup, Reyes, London e Phil estavam na entrada da rua atirando as flechas de madeira. Jake aproveitou e pegou um pedaço de madeira na entrada da marcenaria e começou a bater loucamente o gigante roxo.')
                time.sleep(6)
                print ('-Jake: CE ACHA QUE CE É QUEM PRA MEXE COM MEUS AMIGOS.')
                time.sleep(3)
                print('Troup leva Komissor ao médico que estava no estábulo do rancho do Sr. Dickens.')
                time.sleep(3)
                print('Em Nockville, Jake com os outros dois sobreviventes que ficaram na cidade armam uma fogueira enorme para queimar o monstro. Cada um com seu whisky brinda a vitória da cidade. ')
                time.sleep(4)
    elif esc61==2:
        time.sleep(1)
        print('-Troup: Pior que não xerife, o que você pensa?')
        time.sleep(2)
        print('-Xerife: Pensei em fazer uma barricada e armar os melhores atiradores nos telhados. Armar umas armadilhas pela cidade também.')
        time.sleep(3)
        print('-Troup: Ele é resistente aos tiros...')
        time.sleep(2)
        print('-Xerife: E como vamos mata-lo?')
        time.sleep(2)
        print('-Troup: Que tal distrair ele para as armadilhas? Fica no solo, os mais velozes e os outros ficam nos telhados para dar a posição do monstro.')
        time.sleep(3)
        print('-Xerife: Uma boa idéia, vamos iniciar os trabalhos')
        time.sleep(2)
        print('O dia ia passando e os guerreiros de Nockville iam se preparando, como a cidade estava vazia e o xerife permitiu, eles entraram em diversos estabelecimentos para pegar o que seria útil e formar uma armadura improvisada.')
        time.sleep(5)
        print ('Começou a anoitecer, a equipe estava separada e cada um no lugar marcado. Komissor e o delegado armaram diversas armadilhas com facas. ')
        time.sleep(3)
        print('Phil e Jake estavam juntos de alguns civis em telhados pela cidade. Troup, Komissor, xerife, delegado e dois ex-militares estavam separados, mas nas duas entradas da cidade. Que o terreno plano ajudava a vigia. O frio na barriga era presente em todos, parecia que o dia não passava.')
        time.sleep(5)
        print('Até que após anoitecer, finalmente escutam o que esperavam, mas não queriam ouvir: “MEU DEUS O QUE É AQUILO NO CÉU? ”. Jake avista e berra: “É ELE! ”')
        time.sleep(3)
        print('O monstro se aproxima e pisa no solo, e já começa a disparar e ir de encontro aos cidadãos de Nockville. Dois civis em telhados ficam em estado de choque e caem lá de cima. Cada um tinha uma armadilha a levar o bicho, xerife levou ele certinho a armadilha de facas colocadas na frente de um mercadinho local. Entrou lá e deu uma risadinha após escutar o barulho da armadilha ativada, para sua surpresa uma imensa mão o puxa pela porta. Fim da linha para o xerife.')
        time.sleep(6)
        print('Alguns até tentavam dar tiros para distrai-lo, mas não adiantava. O delegado após ver a morte de seu melhor amigo que saiu de sua posição e foi de encontro com o monstro. Bom, tadinho dele...')
        time.sleep(4)
        print('A turma estava em 11, e em menos de 3 minutos 4 já estavam fora de combate. ')
        time.sleep(2)
        print('+++++++++++++++++++++++++++++++++++++++++++++++++++++++')
        time.sleep(1)
        print('Escolha a ação de Troup:')
        time.sleep(1)
        print('1. Cada um fica aonde está  \n2. Pede para o grupo se reunir')
        time.sleep(1)
        esc62 = int (input('Escolha:  '))
        print('+++++++++++++++++++++++++++++++++++++++++++++++++++++++')
        time.sleep(1)
        if esc62 == 1:
            time.sleep(1)
            print ('Assustado, Jake escorrega no telhado e quebra algumas telhas. Nisso mais que de pressa o bichano parte para o local, Jake percebe corre para dentro da marcenaria e se esconde atrás de algumas vigas. Komissor estava mais perto do local e vai correndo em direção a eles. Troup um pouco mais distante vai também.')
            time.sleep(3)
            print('Jake segurava o terço que tinha pegado naquele mesmo dia na Igreja, o bicho quebra tudo e estava lá dentro. Localiza Jake e o arremessa para o fundo da marcenaria. Jake extremamente machucado pegou um pedaço de madeira pontiagudo que foi gerado após o monstro o tacar na parede. E assim que o bichano chega perto, Jake enfia a madeira e roda. O monstro solta um grunhido e joga o caipira no meio da rua, porém era visível que ele estava sangrando.')
            time.sleep(5)
            print('+++++++++++++++++++++++++++++++++++++++++++++++++++++++')
            time.sleep(1)
            print ('Escolha a ação de Troup')
            time.sleep(1)
            print('1. Vai até Jake e pede para o Komissor ir enfrentar o bicho \n2.Vai até o bicho e pede para o Komissor ajudar o Jake')
            time.sleep(2)
            esc63 = int(input('Escolha:  '))
            print('+++++++++++++++++++++++++++++++++++++++++++++++++++++++')
            time.sleep(1)
            if esc63 == 1:
                time.sleep(0.5)
                print ('-Troup: Komissor, tenta distrair o bicho, vou até o Jake.')
                time.sleep(2)
                print ('-Komissor: Ok')
                time.sleep(1)
                print('Troup chega na rua e segura Jake, quase sem vida.')
                time.sleep(2)
                print('-Troup: Jake, mantém o olho aberto, firme, firme. Você não é um homem de fé agora?')
                time.sleep(2)
                print ('-Jake: eta éé for...te memo maaaas...mas.. da madeirada madeira..nele...')
                time.sleep(2)
                print('-Troup: Que? ')
                time.sleep(1)
                print('-Jake: Ele..e.. não éééé.. i..mune.. a madeira')
                time.sleep(2)
                print('Nisso Troup, vai correndo a marcenaria e vê o bicho indo em direção a Komissor já machucado mas para sua surpresa, o bicho estava sangrando e lento.')
                time.sleep(2)
                print('Troup pega um pedaço de madeira pontiaguda que achou no chão e pula nas costas e começa a enfincar no monstro inúmeras vezes. Finalmente o gigante estava desmoronando. ')
                time.sleep(2)
                print ('-Komissor: nós conseguimos meu amigo...')
                time.sleep(2)
                print ('-Troup: Cacete, nós conseguimos')
                time.sleep(2)
                print('Troup leva Jake ao médico que estava no estábulo do rancho do Sr. Dickens.')
                time.sleep(3)
                print('Em Nockville, Komissor com os outros dois sobreviventes que ficaram na cidade armam uma fogueira enorme para queimar o monstro. Cada um com seu whisky brinda a vitória da cidade. ')
            elif esc63 == 2:
                #-40 de saúde
                time.sleep(0.5)
                print('-Troup: Komissor, vai ver o Jake, vou distrair o bicho.')
                time.sleep(1)
                print('-Komissor: Ok')
                time.sleep(1)
                print('Komissor chega na rua e segura Jake, quase sem vida.')
                time.sleep(2)
                print('-Komissor: Caipira, mantém o olho aberto, firme, aguenta as pontas.')
                time.sleep(2)
                print('-Jake: eta éé for...te memo maaaas...mas.. da madeirada madeira..nele...')
                time.sleep(2)
                print('-Komissor: Não entendi caipira')
                time.sleep(2)
                print('-Jake: Da...aa.. madeira..da nelee..')
                time.sleep(2)
                print('Nisso Komissor, vai correndo a marcenaria e vê o bicho indo em direção a Troup já machucado mas para sua surpresa, o bicho estava sangrando e lento.')
                time.sleep(2)
                print('Komissor pega um pedaço de madeira pontiaguda que achou no chão e pula nas costas e começa a enfincar no monstro inúmeras vezes. Finalmente o gigante estava desmoronando. ')
                time.sleep(3)
                print('-Troup: Parece que conseguimos')
                time.sleep(2)
                print('-Komissor: Morra seu verme!!')
                time.sleep(2)
                print('Troup leva Jake ao médico que estava no estábulo do rancho do Sr. Dickens.')
                time.sleep(3)
                print('Em Nockville, Komissor com os outros dois sobreviventes que ficaram na cidade armam uma fogueira enorme para queimar o monstro. Cada um com seu whisky brinda a vitória da cidade.')
                
        elif esc62 ==2:
            time.sleep(1)
            print('-Troup: Atenção, vamos nos reunir. Não façam barulho.')
            time.sleep(2)
            print('Todos estavam no Saloon, pensando no que poderia ser feito. O desespero era visível. Antes que eles tivessem a oportunidade de discutir alguma estratégia. Eles escutam o barulho pesado da pisada do gigante. ')
            time.sleep(4)
            print ('Cada um sai para um canto, Komissor se esconde e observa o bicho. Ele destrói a entrada do Saloon porém aquela entrada tinha um pedaço firme de madeira que Phil nunca consertou apesar do povo reclamar. Komissor percebe que o bicho jorrou um liquido laranja assim que passou por ali. Mais que de pressa ele saiu correndo gritando “MADEIRA MACHUCA ELE, MADEIRA MACHUCA ELE”.')
            time.sleep(6)
            print('Com os gritos, não havia dúvida quem seria perseguido pelo bicho. Jake que estava ao lado de Troup lembrou que na loja de armas, vendiam arco e flechas para “treino” em que a ponta das flechas eram de madeira.')
            time.sleep(4)
            print('+++++++++++++++++++++++++++++++++++++++++++++++++++++++')
            time.sleep(1)
            print ('Escolha a ação de Troup')
            time.sleep(1)
            print('1. Fala para Jake ir buscar arcos e flechas, enquanto isso vá ajudar Komissor \n2. Vai buscar os arcos e flechas e deixe Jake ajudar Komissor.')
            time.sleep(2)
            esc66 = int(input('Escolha:  '))
            print('+++++++++++++++++++++++++++++++++++++++++++++++++++++++')
            time.sleep(1)
            
            if esc66 == 1:
                time.sleep(1)
                print('-Troup: Jake, vá buscar esses arcos e traga o mais rápido possível, se for o caso dê alguns aos London e ao Reyes (ex militares). Vai !!')
                time.sleep(3)
                print('-Jake: Bele')
                time.sleep(2)
                print('Komissor estava levando o monstro a marcenaria, Troup ia pelo flanco acompanhando até que o bichano acerta um tiro laser nas pernas de Komissor que berrava de dor, quando o bicho se aproximou para finalizar o alemão, se escuta um grito do além: “PAU NESSE FÊI LASQUERAAA”')
                time.sleep(4)
                print('Jake, Reyes, London e Phil estavam na entrada da rua atirando as flechas de madeira. Troup aproveitou e pegou um pedaço pontiagudo de madeira na entrada da marcenaria para finalizar o gigante roxo.')
                time.sleep(3)
                print('Troup leva Komissor ao médico que estava no estábulo do rancho do Sr. Dickens.')
                time.sleep(3)
                print('Em Nockville, Jake com os outros dois sobreviventes que ficaram na cidade armam uma fogueira enorme para queimar o monstro. Cada um com seu whisky brinda a vitória da cidade. ')
                time.sleep(2)
                
            elif esc66 == 2:
                time.sleep(1)
                print('-Troup: Jake, vá ajudar o Komissor. Acompanha ele na corrida pelo flanco da rua')
                time.sleep(3)
                print ('-Jake: Ok, não é melhor eu ir pegar as armas que sou mais rápido?')
                time.sleep(3)
                print ('Komissor estava levando o monstro a marcenaria, Troup ia pelo flanco acompanhando até que o bichano acerta um tiro laser nas pernas de Komissor que berrava de dor, quando o bicho se aproximou para finalizar o alemão, se escuta um grito do além: “PEGA EU FEIÃO”. ')
                time.sleep(5)
                print('O monstro largou o Komissor e foi pegar Jake, porém nesse momento Troup, Reyes, London e Phil estavam na entrada da rua atirando as flechas de madeira. Jake aproveitou e pegou um pedaço de madeira na entrada da marcenaria e começou a bater loucamente o gigante roxo.')
                time.sleep(6)
                print ('-Jake: CE ACHA QUE CE É QUEM PRA MEXE COM MEUS AMIGOS.')
                time.sleep(3)
                print('Troup leva Komissor ao médico que estava no estábulo do rancho do Sr. Dickens.')
                time.sleep(3)
                print('Em Nockville, Jake com os outros dois sobreviventes que ficaram na cidade armam uma fogueira enorme para queimar o monstro. Cada um com seu whisky brinda a vitória da cidade. ')
                time.sleep(4)
if esc60 == 2:
    time.sleep(1)
    print('Troup fala para seus amigos que o certo seria ‘’interceptar’’ o monstro, assim não permitindo que ele não chegue na cidade. Pela cara dos seus amigos, Troup percebeu que eles não acharam a ideia muito inteligente.')
    time.sleep(4)
    print('-Jake: Discurpa meu irmão mai isso é uma decisão estupida, nói não teria vantagi contra ele')
    time.sleep(3)
    print('-Komissor: Eu também não concordo com essa ideia, se esconder atrás de rochas, é muito menos vantajoso do que se esconder por casa e pelas cidades.')
    time.sleep(4)
    print('-Troup: Se ele demolir casas, os escombros nos matariam.')
    time.sleep(2)
    print('-Jake: Issu é verdade verdadeira')
    time.sleep(1)
    print('-Komissor: Mas e em campo livre, como seria? Seríamos alvos fáceis.')
    time.sleep(3)
    print('-Troup: O que você sugere?')
    time.sleep(2)
    print ('-Komissor: Armadilhas pela cidade, cada um em um ponto para distrai-lo e usar os telhados para identificar a posição dele.')
    time.sleep(4)
    print('-Troup: Droga, to começando a concordar com você. Semelhante ao que fizemos em Punta Orgullo?')
    time.sleep(3)
    print('-Komissor: Escalera, para pegar os bandidos do Reyes.')
    time.sleep(2)
    print('-Jake: Uceis são brabo')
    time.sleep(2)
    print('-Troup: Ok meus amigos. Vou conversar com o Cartwright')
    time.sleep(3)
    print ('Troup e Komissor vão de encontro ao Xerife Cartwright para conversar sobre as táticas e do que vai ser da cidade no dia seguinte')
    time.sleep(3)
    print('Xerife pergunta se Troup tem alguma estratégia:')
    time.sleep(2)
    print('+++++++++++++++++++++++++++++++++++++++++++++++++++++++')
    time.sleep(1)
    print('Escolha a ação de Troup:')
    time.sleep(1)
    print('1. Tenho uma estratégia  \n2. Não tenho nada definido')
    time.sleep(1)
    esc61 = int(input('Escolha:  '))
    print('+++++++++++++++++++++++++++++++++++++++++++++++++++++++')
    time.sleep(1)
    if esc61 == 1:
        time.sleep(1)
        print('-Troup: Sim xerife, eu pensei em separar algumas armadilhas nos arredores da cidade e dispersar os homens. Deixam alguns dos piores atiradores nas partes altas de cada rua para avisar caso o bichano estiver vindo. E os velocistas aqui no papel cruel de distrair o bicho. Pois como ele é imune a bala penso que apenas com objetos cortantes vamos conseguir mata-lo.')
        time.sleep(5)
        print('-Xerife: É muito arriscado, não é melhor deixar alguns atiradores a uma boa distância?')
        time.sleep(2)
        print('-Troup: Ele resiste a tiros...')
        time.sleep(2)
        print('O dia ia passando e os guerreiros de Nockville iam se preparando, como a cidade estava vazia e o xerife permitiu, eles entraram em diversos estabelecimentos para pegar o que seria útil e formar uma armadura improvisada.')
        time.sleep(3)
        print ('Começou a anoitecer, a equipe estava separada e cada um no lugar marcado. Komissor e o delegado armaram diversas armadilhas com facas. ')
        time.sleep(2)
        print('Phil e Jake estavam juntos de alguns civis em telhados pela cidade. Troup, Komissor, xerife, delegado e dois ex-militares estavam separados, mas nas duas entradas da cidade. Que o terreno plano ajudava a vigia. O frio na barriga era presente em todos, parecia que o dia não passava.')
        time.sleep(4)
        print('Até que após anoitecer, finalmente escutam o que esperavam, mas não queriam ouvir: “MEU DEUS O QUE É AQUILO NO CÉU? ”. Jake avista e berra: “É ELE! ”')
        time.sleep(3)
        print('O monstro pisa no solo, e já começa a disparar e ir de encontro aos cidadãos de Nockville. Dois civis em telhados ficam em estado de choque e caem lá de cima. Cada um tinha uma armadilha a levar o bicho, xerife levou ele certinho a armadilha de facas colocadas na frente de um mercadinho local. Entrou lá e deu uma risadinha após escutar o barulho da armadilha ativada, para sua surpresa uma imensa mão o puxa pela porta. Fim da linha para o xerife.')
        time.sleep(5)
        print('Alguns até tentavam dar tiros para distrai-lo, mas não adiantava. O delegado após ver a morte de seu melhor amigo que saiu de sua posição e foi de encontro com o monstro. Bom, coitado...')
        time.sleep(4)
        print('A turma estava em 11, e em menos de 3 minutos 4 já estavam fora de combate. ')
        time.sleep(1)
        print('+++++++++++++++++++++++++++++++++++++++++++++++++++++++')
        time.sleep(1)
        print('Escolha a ação de Troup')
        time.sleep(1)
        print('1. Cada um fica aonde está  \n2. Pede para o grupo se reunir')
        time.sleep(1)
        esc62 = int (input('Escolha:  '))
        print('+++++++++++++++++++++++++++++++++++++++++++++++++++++++')
        time.sleep(1)
        if esc62 == 1:
            time.sleep(1)
            print ('Assustado, Jake escorrega no telhado e quebra algumas telhas. Nisso mais que de pressa o bichano parte para o local, Jake percebe corre para dentro da marcenaria e se esconde atrás de algumas vigas. Komissor estava mais perto do local e vai correndo em direção a eles. Troup um pouco mais distante vai também.')
            time.sleep(3)
            print('Jake segurava o terço que tinha pegado naquele mesmo dia na Igreja, o bicho quebra tudo e estava lá dentro. Localiza Jake e o arremessa para o fundo da marcenaria. Jake extremamente machucado pegou um pedaço de madeira pontiagudo que foi gerado após o monstro o tacar na parede. E assim que o bichano chega perto, Jake enfia a madeira e roda. O monstro solta um grunhido e joga o caipira no meio da rua, porém era visível que ele estava sangrando.')
            time.sleep(5)
            print('+++++++++++++++++++++++++++++++++++++++++++++++++++++++')
            time.sleep(1)
            print ('Escolha a ação de Troup')
            time.sleep(1)
            print('1. Vai até Jake e pede para o Komissor ir enfrentar o bicho \n2.Vai até o bicho e pede para o Komissor ajudar o Jake')
            time.sleep(2)
            esc63 = int(input('Escolha:   '))
            print('+++++++++++++++++++++++++++++++++++++++++++++++++++++++')
            time.sleep(1)
            if esc63 == 1:
                time.sleep(0.5)
                print ('-Troup: Komissor, tenta distrair o bicho, vou até o Jake.')
                time.sleep(2)
                print ('-Komissor: Ok')
                time.sleep(1)
                print('Troup chega na rua e segura Jake, quase sem vida.')
                time.sleep(2)
                print('-Troup: Jake, mantém o olho aberto, firme, firme. Você não é um homem de fé agora?')
                time.sleep(2)
                print ('-Jake: eta éé for...te memo maaaas...mas.. da madeirada madeira..nele...')
                time.sleep(2)
                print('-Troup: Que? ')
                time.sleep(1)
                print('-Jake: Ele..e.. não éééé.. i..mune.. a madeira')
                time.sleep(2)
                print('Nisso Troup, vai correndo a marcenaria e vê o bicho indo em direção a Komissor já machucado mas para sua surpresa, o bicho estava sangrando e lento.')
                time.sleep(2)
                print('Troup pega um pedaço de madeira pontiaguda que achou no chão e pula nas costas e começa a enfincar no monstro inúmeras vezes. Finalmente o gigante estava desmoronando. ')
                time.sleep(2)
                print ('-Komissor: nós conseguimos meu amigo...')
                time.sleep(2)
                print ('-Troup: Cacete, nós conseguimos')
                time.sleep(2)
                print('Troup leva Jake ao médico que estava no estábulo do rancho do Sr. Dickens.')
                time.sleep(3)
                print('Em Nockville, Komissor com os outros dois sobreviventes que ficaram na cidade armam uma fogueira enorme para queimar o monstro. Cada um com seu whisky brinda a vitória da cidade. ')
            elif esc63 == 2:
                #-40 de saúde
                time.sleep(0.5)
                print('-Troup: Komissor, vai ver o Jake, vou distrair o bicho.')
                time.sleep(1)
                print('-Komissor: Ok')
                time.sleep(1)
                print('Komissor chega na rua e segura Jake, quase sem vida.')
                time.sleep(2)
                print('-Komissor: Caipira, mantém o olho aberto, firme, aguenta as pontas.')
                time.sleep(2)
                print('-Jake: eta éé for...te memo maaaas...mas.. da madeirada madeira..nele...')
                time.sleep(2)
                print('-Komissor: Não entendi caipira')
                time.sleep(2)
                print('-Jake: Da...aa.. madeira..da nelee..')
                time.sleep(2)
                print('Nisso Komissor, vai correndo a marcenaria e vê o bicho indo em direção a Troup já machucado mas para sua surpresa, o bicho estava sangrando e lento.')
                time.sleep(2)
                print('Komissor pega um pedaço de madeira pontiaguda que achou no chão e pula nas costas e começa a enfincar no monstro inúmeras vezes. Finalmente o gigante estava desmoronando. ')
                time.sleep(3)
                print('-Troup: Parece que conseguimos')
                time.sleep(2)
                print('-Komissor: Morra seu verme!!')
                time.sleep(2)
                print('Troup leva Jake ao médico que estava no estábulo do rancho do Sr. Dickens.')
                time.sleep(3)
                print('Em Nockville, Komissor com os outros dois sobreviventes que ficaram na cidade armam uma fogueira enorme para queimar o monstro. Cada um com seu whisky brinda a vitória da cidade.') 
        elif esc62 ==2:
            time.sleep(1)
            print('-Troup: Atenção, vamos nos reunir. Não façam barulho.')
            time.sleep(2)
            print('Todos estavam no Saloon, pensando no que poderia ser feito. O desespero era visível. Antes que eles tivessem a oportunidade de discutir alguma estratégia. Eles escutam o barulho pesado da pisada do gigante. ')
            time.sleep(4)
            print ('Cada um sai para um canto, Komissor se esconde e observa o bicho. Ele destrói a entrada do Saloon porém aquela entrada tinha um pedaço firme de madeira que Phil nunca consertou apesar do povo reclamar. Komissor percebe que o bicho jorrou um liquido laranja assim que passou por ali. Mais que de pressa ele saiu correndo gritando “MADEIRA MACHUCA ELE, MADEIRA MACHUCA ELE”.')
            time.sleep(6)
            print('Com os gritos, não havia dúvida quem seria perseguido pelo bicho. Jake que estava ao lado de Troup lembrou que na loja de armas, vendiam arco e flechas para “treino” em que a ponta das flechas eram de madeira.')
            time.sleep(4)
            print('+++++++++++++++++++++++++++++++++++++++++++++++++++++++')
            time.sleep(1)
            print ('Escolha a ação de Troup:  ')
            time.sleep(1)
            print('1. Fala para Jake ir buscar arcos e flechas, enquanto isso vá ajudar Komissor \n2. Vai buscar os arcos e flechas e deixe Jake ajudar Komissor.')
            time.sleep(2)
            esc64 = int(input('Escolha:'))
            print('+++++++++++++++++++++++++++++++++++++++++++++++++++++++')
            time.sleep(1)    
            if esc64 == 1:
                time.sleep(1)
                print('-Troup: Jake, vá buscar esses arcos e traga o mais rápido possível, se for o caso dê alguns aos London e ao Reyes (ex militares). Vai !!')
                time.sleep(3)
                print('-Jake: Bele')
                time.sleep(2)
                print('Komissor estava levando o monstro a marcenaria, Troup ia pelo flanco acompanhando até que o bichano acerta um tiro laser nas pernas de Komissor que berrava de dor, quando o bicho se aproximou para finalizar o alemão, se escuta um grito do além: “PAU NESSE FÊI LASQUERAAA”')
                time.sleep(4)
                print('Jake, Reyes, London e Phil estavam na entrada da rua atirando as flechas de madeira. Troup aproveitou e pegou um pedaço pontiagudo de madeira na entrada da marcenaria para finalizar o gigante roxo.')
                time.sleep(3)
                print('Troup leva Komissor ao médico que estava no estábulo do rancho do Sr. Dickens.')
                time.sleep(3)
                print('Em Nockville, Jake com os outros dois sobreviventes que ficaram na cidade armam uma fogueira enorme para queimar o monstro. Cada um com seu whisky brinda a vitória da cidade. ')
                time.sleep(2)
            elif esc64 == 2:
                time.sleep(1)
                print('-Troup: Jake, vá ajudar o Komissor. Acompanha ele na corrida pelo flanco da rua')
                time.sleep(3)
                print ('-Jake: Ok, não é melhor eu ir pegar as armas que sou mais rápido?')
                time.sleep(3)
                print ('Komissor estava levando o monstro a marcenaria, Troup ia pelo flanco acompanhando até que o bichano acerta um tiro laser nas pernas de Komissor que berrava de dor, quando o bicho se aproximou para finalizar o alemão, se escuta um grito do além: “PEGA EU FEIÃO”. ')
                time.sleep(5)
                print('O monstro largou o Komissor e foi pegar Jake, porém nesse momento Troup, Reyes, London e Phil estavam na entrada da rua atirando as flechas de madeira. Jake aproveitou e pegou um pedaço de madeira na entrada da marcenaria e começou a bater loucamente o gigante roxo.')
                time.sleep(6)
                print ('-Jake: CE ACHA QUE CE É QUEM PRA MEXE COM MEUS AMIGOS.')
                time.sleep(3)
                print('Troup leva Komissor ao médico que estava no estábulo do rancho do Sr. Dickens.')
                time.sleep(3)
                print('Em Nockville, Jake com os outros dois sobreviventes que ficaram na cidade armam uma fogueira enorme para queimar o monstro. Cada um com seu whisky brinda a vitória da cidade. ')
                time.sleep(4)
    elif esc61==2:
        time.sleep(1)
        print('-Troup: Pior que não xerife, o que você pensa?')
        time.sleep(2)
        print('-Xerife: Pensei em fazer uma barricada e armar os melhores atiradores nos telhados. Armar umas armadilhas pela cidade também.')
        time.sleep(3)
        print('-Troup: Ele é resistente aos tiros...')
        time.sleep(2)
        print('-Xerife: E como vamos mata-lo?')
        time.sleep(2)
        print('-Troup: Que tal distrair ele para as armadilhas? Fica no solo, os mais velozes e os outros ficam nos telhados para dar a posição do monstro.')
        time.sleep(3)
        print('-Xerife: Uma boa idéia, vamos iniciar os trabalhos')
        time.sleep(2)
        print('O dia ia passando e os guerreiros de Nockville iam se preparando, como a cidade estava vazia e o xerife permitiu, eles entraram em diversos estabelecimentos para pegar o que seria útil e formar uma armadura improvisada.')
        time.sleep(5)
        print ('Começou a anoitecer, a equipe estava separada e cada um no lugar marcado. Komissor e o delegado armaram diversas armadilhas com facas. ')
        time.sleep(3)
        print('Phil e Jake estavam juntos de alguns civis em telhados pela cidade. Troup, Komissor, xerife, delegado e dois ex-militares estavam separados, mas nas duas entradas da cidade. Que o terreno plano ajudava a vigia. O frio na barriga era presente em todos, parecia que o dia não passava.')
        time.sleep(5)
        print('Até que após anoitecer, finalmente escutam o que esperavam, mas não queriam ouvir: “MEU DEUS O QUE É AQUILO NO CÉU? ”. Jake avista e berra: “É ELE! ”')
        time.sleep(3)
        print('O monstro se aproxima e pisa no solo, e já começa a disparar e ir de encontro aos cidadãos de Nockville. Dois civis em telhados ficam em estado de choque e caem lá de cima. Cada um tinha uma armadilha a levar o bicho, xerife levou ele certinho a armadilha de facas colocadas na frente de um mercadinho local. Entrou lá e deu uma risadinha após escutar o barulho da armadilha ativada, para sua surpresa uma imensa mão o puxa pela porta. Fim da linha para o xerife.')
        time.sleep(6)
        print('Alguns até tentavam dar tiros para distrai-lo, mas não adiantava. O delegado após ver a morte de seu melhor amigo que saiu de sua posição e foi de encontro com o monstro. Bom, tadinho dele...')
        time.sleep(4)
        print('A turma estava em 11, e em menos de 3 minutos 4 já estavam fora de combate. ')
        time.sleep(2)
        print('+++++++++++++++++++++++++++++++++++++++++++++++++++++++')
        time.sleep(1)
        print('Escolha a ação de Troup:')
        time.sleep(1)
        print('1. Cada um fica aonde está  \n2. Pede para o grupo se reunir')
        time.sleep(1)
        esc62 = int (input('Escolha:  '))
        print('+++++++++++++++++++++++++++++++++++++++++++++++++++++++')
        time.sleep(1)
        if esc62 == 1:
            time.sleep(1)
            print ('Assustado, Jake escorrega no telhado e quebra algumas telhas. Nisso mais que de pressa o bichano parte para o local, Jake percebe corre para dentro da marcenaria e se esconde atrás de algumas vigas. Komissor estava mais perto do local e vai correndo em direção a eles. Troup um pouco mais distante vai também.')
            time.sleep(3)
            print('Jake segurava o terço que tinha pegado naquele mesmo dia na Igreja, o bicho quebra tudo e estava lá dentro. Localiza Jake e o arremessa para o fundo da marcenaria. Jake extremamente machucado pegou um pedaço de madeira pontiagudo que foi gerado após o monstro o tacar na parede. E assim que o bichano chega perto, Jake enfia a madeira e roda. O monstro solta um grunhido e joga o caipira no meio da rua, porém era visível que ele estava sangrando.')
            time.sleep(5)
            print('+++++++++++++++++++++++++++++++++++++++++++++++++++++++')
            time.sleep(1)
            print ('Escolha a ação de Troup')
            time.sleep(1)
            print('1. Vai até Jake e pede para o Komissor ir enfrentar o bicho \n2.Vai até o bicho e pede para o Komissor ajudar o Jake')
            time.sleep(2)
            esc63 = int(input('Escolha:  '))
            print('+++++++++++++++++++++++++++++++++++++++++++++++++++++++')
            time.sleep(1)
            if esc63 == 1:
                time.sleep(0.5)
                print ('-Troup: Komissor, tenta distrair o bicho, vou até o Jake.')
                time.sleep(2)
                print ('-Komissor: Ok')
                time.sleep(1)
                print('Troup chega na rua e segura Jake, quase sem vida.')
                time.sleep(2)
                print('-Troup: Jake, mantém o olho aberto, firme, firme. Você não é um homem de fé agora?')
                time.sleep(2)
                print ('-Jake: eta éé for...te memo maaaas...mas.. da madeirada madeira..nele...')
                time.sleep(2)
                print('-Troup: Que? ')
                time.sleep(1)
                print('-Jake: Ele..e.. não éééé.. i..mune.. a madeira')
                time.sleep(2)
                print('Nisso Troup, vai correndo a marcenaria e vê o bicho indo em direção a Komissor já machucado mas para sua surpresa, o bicho estava sangrando e lento.')
                time.sleep(2)
                print('Troup pega um pedaço de madeira pontiaguda que achou no chão e pula nas costas e começa a enfincar no monstro inúmeras vezes. Finalmente o gigante estava desmoronando. ')
                time.sleep(2)
                print ('-Komissor: nós conseguimos meu amigo...')
                time.sleep(2)
                print ('-Troup: Cacete, nós conseguimos')
                time.sleep(2)
                print('Troup leva Jake ao médico que estava no estábulo do rancho do Sr. Dickens.')
                time.sleep(3)
                print('Em Nockville, Komissor com os outros dois sobreviventes que ficaram na cidade armam uma fogueira enorme para queimar o monstro. Cada um com seu whisky brinda a vitória da cidade. ')
            elif esc63 == 2:
                #-40 de saúde
                time.sleep(0.5)
                print('-Troup: Komissor, vai ver o Jake, vou distrair o bicho.')
                time.sleep(1)
                print('-Komissor: Ok')
                time.sleep(1)
                print('Komissor chega na rua e segura Jake, quase sem vida.')
                time.sleep(2)
                print('-Komissor: Caipira, mantém o olho aberto, firme, aguenta as pontas.')
                time.sleep(2)
                print('-Jake: eta éé for...te memo maaaas...mas.. da madeirada madeira..nele...')
                time.sleep(2)
                print('-Komissor: Não entendi caipira')
                time.sleep(2)
                print('-Jake: Da...aa.. madeira..da nelee..')
                time.sleep(2)
                print('Nisso Komissor, vai correndo a marcenaria e vê o bicho indo em direção a Troup já machucado mas para sua surpresa, o bicho estava sangrando e lento.')
                time.sleep(2)
                print('Komissor pega um pedaço de madeira pontiaguda que achou no chão e pula nas costas e começa a enfincar no monstro inúmeras vezes. Finalmente o gigante estava desmoronando. ')
                time.sleep(3)
                print('-Troup: Parece que conseguimos')
                time.sleep(2)
                print('-Komissor: Morra seu verme!!')
                time.sleep(2)
                print('Troup leva Jake ao médico que estava no estábulo do rancho do Sr. Dickens.')
                time.sleep(3)
                print('Em Nockville, Komissor com os outros dois sobreviventes que ficaram na cidade armam uma fogueira enorme para queimar o monstro. Cada um com seu whisky brinda a vitória da cidade.')
                
        elif esc62 ==2:
            time.sleep(1)
            print('-Troup: Atenção, vamos nos reunir. Não façam barulho.')
            time.sleep(2)
            print('Todos estavam no Saloon, pensando no que poderia ser feito. O desespero era visível. Antes que eles tivessem a oportunidade de discutir alguma estratégia. Eles escutam o barulho pesado da pisada do gigante. ')
            time.sleep(4)
            print ('Cada um sai para um canto, Komissor se esconde e observa o bicho. Ele destrói a entrada do Saloon porém aquela entrada tinha um pedaço firme de madeira que Phil nunca consertou apesar do povo reclamar. Komissor percebe que o bicho jorrou um liquido laranja assim que passou por ali. Mais que de pressa ele saiu correndo gritando “MADEIRA MACHUCA ELE, MADEIRA MACHUCA ELE”.')
            time.sleep(6)
            print('Com os gritos, não havia dúvida quem seria perseguido pelo bicho. Jake que estava ao lado de Troup lembrou que na loja de armas, vendiam arco e flechas para “treino” em que a ponta das flechas eram de madeira.')
            time.sleep(4)
            print('+++++++++++++++++++++++++++++++++++++++++++++++++++++++')
            time.sleep(1)
            print ('Escolha a ação de Troup')
            time.sleep(1)
            print('1. Fala para Jake ir buscar arcos e flechas, enquanto isso vá ajudar Komissor \n2. Vai buscar os arcos e flechas e deixe Jake ajudar Komissor.')
            time.sleep(2)
            esc66 = int(input('Escolha:  '))
            print('+++++++++++++++++++++++++++++++++++++++++++++++++++++++')
            time.sleep(1)
            
            if esc66 == 1:
                time.sleep(1)
                print('-Troup: Jake, vá buscar esses arcos e traga o mais rápido possível, se for o caso dê alguns aos London e ao Reyes (ex militares). Vai !!')
                time.sleep(3)
                print('-Jake: Bele')
                time.sleep(2)
                print('Komissor estava levando o monstro a marcenaria, Troup ia pelo flanco acompanhando até que o bichano acerta um tiro laser nas pernas de Komissor que berrava de dor, quando o bicho se aproximou para finalizar o alemão, se escuta um grito do além: “PAU NESSE FÊI LASQUERAAA”')
                time.sleep(4)
                print('Jake, Reyes, London e Phil estavam na entrada da rua atirando as flechas de madeira. Troup aproveitou e pegou um pedaço pontiagudo de madeira na entrada da marcenaria para finalizar o gigante roxo.')
                time.sleep(3)
                print('Troup leva Komissor ao médico que estava no estábulo do rancho do Sr. Dickens.')
                time.sleep(3)
                print('Em Nockville, Jake com os outros dois sobreviventes que ficaram na cidade armam uma fogueira enorme para queimar o monstro. Cada um com seu whisky brinda a vitória da cidade. ')
                time.sleep(2)
                
            elif esc66 == 2:
                time.sleep(1)
                print('-Troup: Jake, vá ajudar o Komissor. Acompanha ele na corrida pelo flanco da rua')
                time.sleep(3)
                print ('-Jake: Ok, não é melhor eu ir pegar as armas que sou mais rápido?')
                time.sleep(3)
                print ('Komissor estava levando o monstro a marcenaria, Troup ia pelo flanco acompanhando até que o bichano acerta um tiro laser nas pernas de Komissor que berrava de dor, quando o bicho se aproximou para finalizar o alemão, se escuta um grito do além: “PEGA EU FEIÃO”. ')
                time.sleep(5)
                print('O monstro largou o Komissor e foi pegar Jake, porém nesse momento Troup, Reyes, London e Phil estavam na entrada da rua atirando as flechas de madeira. Jake aproveitou e pegou um pedaço de madeira na entrada da marcenaria e começou a bater loucamente o gigante roxo.')
                time.sleep(6)
                print ('-Jake: CE ACHA QUE CE É QUEM PRA MEXE COM MEUS AMIGOS.')
                time.sleep(3)
                print('Troup leva Komissor ao médico que estava no estábulo do rancho do Sr. Dickens.')
                time.sleep(3)
                print('Em Nockville, Jake com os outros dois sobreviventes que ficaram na cidade armam uma fogueira enorme para queimar o monstro. Cada um com seu whisky brinda a vitória da cidade. ')
                time.sleep(4)
     
time.sleep(2)
print ("---------------------------------------------------------------------------------------------------------------------------------------------------")
time.sleep(1)
print ("    FINAL")
time.sleep(1)
print('No dia seguinte, o clima de felicidade era visível, mesmo com muito prejuízo e destruição, a aventura foi concluída. ')
time.sleep(3)
print('A madrugada foi longa, Phil não permitiu que comessem a carne do bicho estranho.')
time.sleep(2)
print('-Phil: Pelo meu irmão esse desgraçado tem que continuar queimando ate o fogo do inferno. ')
time.sleep(3)
print('Que foi totalmente queimado e enterrado em algum canto de Nockville.')
time.sleep(2)
print('Essa foi a história de Nockville, não ouso chamar de Lenda pois cada um sabe crê naquilo que lhe deseja. ')
time.sleep(4)

print('+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+')
time.sleep(2)
print('Feito por: Bruno Queiroz e Yuri Camilo')
                      

                     

            

